'use client'

import                           './globals.css'
// import { Inter }            from 'next/font/google'
import Banner               from './components/Banner'
import { PyScriptProvider } from 'pyscript-react' 
import { ErrorBoundary }    from './components/ErrorBoundary';

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <>
        <html lang="en">
              <head>
                    <link rel="shortcut icon" href="#" />
              </head>
              <body className="MainContainer">
                  <ErrorBoundary fallback="Error">
                        <Banner />
                        <ErrorBoundary  fallback={children}>
                              <PyScriptProvider>
                                    <ErrorBoundary fallback="Error">
                                          <py-config>packages = ["numpy","pandas","matplotlib","scikit-learn","asyncio"]</py-config>
                                    </ErrorBoundary>
                                    {children}
                              </PyScriptProvider>
                        </ErrorBoundary>
                  </ErrorBoundary>     
              </body>
        </html>
    </>
  )
}
